mod ci file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,41 +5,41 @@ on:
   schedule:
     - cron: "0 */2 * * *"
   workflow_dispatch:
-  permissions:
-    contents: write
-  jobs:
-    test_and_fetch:
-      runs-on: ubuntu-latest
-      steps:
-      - name: Checkout repo
-        uses: actions/checkout@v4
-      - name: Use node.JS
-        uses: actions/setup-node@v4
-        with:
-          node-version: "22"
-      - name: Cache Node modules
-        uses: actions/cache@v3
-        with:
-          path: ~/npm
-          key: ${{runner.os}}-node-${{hashFiles('package-lock.json')}}
-      - name : Install Dependencies
-        run: npm ci
-      - name: Fetch Latest Weather
-        run: npm ci
-      - name: Fecth Latest Number
-        env:
-          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
-          WEATHER_CITY: ${{ secrets.CITY}}
-          PORT: ${{ secrets.PORT}}
-        run: node fecthweather.js
-      - name: Commit weather data if changed
-        run: |
-          git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
-          git add /dataweather.json data/weather_log.csv || true
-          git commit -m "ci: update weather data" || echo "No changed to commit"
-          git push || echo "Push failed or no changes"
-      - name: Trigger Render Deploy
-        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
+permissions:
+  contents: write
+jobs:
+  test_and_fetch:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout repo
+      uses: actions/checkout@v4
+    - name: Use node.JS
+      uses: actions/setup-node@v4
+      with:
+        node-version: "22"
+    - name: Cache Node modules
+      uses: actions/cache@v3
+      with:
+        path: ~/npm
+        key: ${{runner.os}}-node-${{hashFiles('package-lock.json')}}
+    - name : Install Dependencies
+      run: npm ci
+    - name: Fetch Latest Weather
+      run: npm ci
+    - name: Fecth Latest Number
+      env:
+        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
+        WEATHER_CITY: ${{ secrets.CITY}}
+        PORT: ${{ secrets.PORT}}
+      run: node fecthweather.js
+    - name: Commit weather data if changed
+      run: |
+        git config user.name "github-actions[bot]"
+        git config user.email "github-actions[bot]@users.noreply.github.com"
+        git add /dataweather.json data/weather_log.csv || true
+        git commit -m "ci: update weather data" || echo "No changed to commit"
+        git push || echo "Push failed or no changes"
+    - name: Trigger Render Deploy
+      run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
 
 
